var cardData = [
    { id: 1, name: "天使ばーば1大堕天使ババエルの彷徨い", attribute: "天使", image: "card/angel1.png", creator: "作者A" },
    { id: 2, name: "天使ばーば2", attribute: "天使", image: "card/angel2.png", creator: "作者B" },
    { id: 3, name: "天使ばーば3", attribute: "天使", image: "card/angel3.png", creator: "作者C" },
    { id: 4, name: "天使ばーば4", attribute: "天使", image: "card/angel4.png", creator: "作者D" },
    { id: 5, name: "天使ばーば5", attribute: "天使", image: "card/angel5.png", creator: "作者E" },
    { id: 6, name: "悪魔ばーば1", attribute: "悪魔", image: "card/demon1.png", creator: "作者F" },
    { id: 7, name: "悪魔ばーば2", attribute: "悪魔", image: "card/demon2.png", creator: "作者G" },
    { id: 8, name: "悪魔ばーば3", attribute: "悪魔", image: "card/demon3.png", creator: "作者H" },
    { id: 9, name: "悪魔ばーば4", attribute: "悪魔", image: "card/demon4.png", creator: "作者I" },
    { id: 10, name: "悪魔ばーば5", attribute: "悪魔", image: "card/demon5.png", creator: "作者J" },
    { id: 11, name: "成金ばーば1", attribute: "成金", image: "card/rich1.png", creator: "作者K" },
    { id: 12, name: "成金ばーば2", attribute: "成金", image: "card/rich2.png", creator: "作者L" },
    { id: 13, name: "成金ばーば3", attribute: "成金", image: "card/rich3.png", creator: "作者M" },
    { id: 14, name: "成金ばーば4", attribute: "成金", image: "card/rich4.png", creator: "作者N" },
    { id: 15, name: "成金ばーば5", attribute: "成金", image: "card/rich5.png", creator: "作者O" },
    // 新しい天使カード
    { id: 16, name: "天使ばーば6", attribute: "天使", image: "card/angel1.png", creator: "作者P" },
    { id: 17, name: "天使ばーば7", attribute: "天使", image: "card/angel2.png", creator: "作者Q" },
    { id: 18, name: "天使ばーば8", attribute: "天使", image: "card/angel3.png", creator: "作者R" },
    { id: 19, name: "天使ばーば9", attribute: "天使", image: "card/angel4.png", creator: "作者S" },
    { id: 20, name: "天使ばーば10", attribute: "天使", image: "card/angel5.png", creator: "作者T" },
    // 新しい悪魔カード
    { id: 21, name: "悪魔ばーば6", attribute: "悪魔", image: "card/demon1.png", creator: "作者U" },
    { id: 22, name: "悪魔ばーば7", attribute: "悪魔", image: "card/demon2.png", creator: "作者V" },
    { id: 23, name: "悪魔ばーば8", attribute: "悪魔", image: "card/demon3.png", creator: "作者W" },
    { id: 24, name: "悪魔ばーば9", attribute: "悪魔", image: "card/demon4.png", creator: "作者X" },
    { id: 25, name: "悪魔ばーば10", attribute: "悪魔", image: "card/demon5.png", creator: "作者Y" },
    // 新しい成金カード
    { id: 26, name: "成金ばーば6", attribute: "成金", image: "card/rich1.png", creator: "作者Z" },
    { id: 27, name: "成金ばーば7", attribute: "成金", image: "card/rich2.png", creator: "作者AA" },
    { id: 28, name: "成金ばーば8", attribute: "成金", image: "card/rich3.png", creator: "作者AB" },
    { id: 29, name: "成金ばーば9", attribute: "成金", image: "card/rich4.png", creator: "作者AC" },
    { id: 30, name: "成金ばーば10", attribute: "成金", image: "card/rich5.png", creator: "作者AD" },
];